BugTracker/BugTracker/Controllers/GuestController.cs
using BugTracker.Data;
using BugTracker.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BugTracker.Controllers
{
    public class GuestController : Controller
    {
        private ApplicationDbContext _db { get; set; }
        private UserManager<ApplicationUser> _userManager { get; set; }
        private RoleManager<IdentityRole> _roleManager { get; set; }


        public GuestController(ApplicationDbContext db, UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager, SignInManager<ApplicationUser> signInManager)
        {
            _db = db;
            _userManager = userManager;
            _roleManager = roleManager;
            
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            ApplicationUser guestUser = await _userManager.FindByNameAsync("guest03@gmail.com");
            return View(guestUser);
        }

        [HttpPost]
        public IActionResult Index(bool re)
        {
            if(re)
            {
                return View("AdminDashboard");
            }
            else
            {
                return View();
            }
        }
    }
}

BugTracker/BugTracker/Views/Guest/Index.cshtml
@using BugTracker.Models
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Authentication;
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@model ApplicationUser
@{
    var signInManager = SignInManager;
    var result = await signInManager.PasswordSignInAsync(Model.Email, "Password!1", isPersistent: false, lockoutOnFailure: false);
    string re = result.Succeeded ? "true" : "false";
}

 <form asp-controller="Guest" asp-action="Index" method="post" id="guestId">
    <input type="hidden" name="re" value="@re"/>
</form>

<script type="text/javascript">document.forms["guestId"].submit();
</script>